import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.xcite.com/media/catalog/product//i/p/iphone_14_5g_-_blue_1_1_1.jpg",
    title: "Apple iPhone 14",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$30000",
    newPrice: "10000",
    company: "Apple",
    color: "blue",
    category: "mobile",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.bWaYLmfcNI21OFZLA_i24gHaHa&pid=Api&P=0&h=180",
    title: "GPS smart watch ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$110",
    newPrice: "100",
    company: "Apple",
    color: "blue",
    category: "watches",
  },

  {
    img: "https://tse1.mm.bing.net/th?id=OIP.ceGMbUG378ujQ34bWC3OLgHaHa&pid=Api&P=0&h=180",
    title: "Apple Mac Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$2000",
    newPrice: "1000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.KyrBu1s2mkrqDl3Bdo8QtAHaHa&pid=Api&P=0&h=180",
    title: "Apple iPhone 14",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1203 reviews)",
    prevPrice: "$30000",
    newPrice: "1000",
    company: "Apple",
    color: "Apple",
    category: "mobile",
  },
  {
    img: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6340/6340244_sd.jpg",
    title: "Apple Watch SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(2300 reviews)",
    prevPrice: "$200",
    newPrice: "110",
    company: "Apple",
    color: "black",
    category: "waches",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.FkYj-LFU5lo4G1eNVwYYFAHaJK&pid=Api&P=0&h=180",
    title: "Samsung Galaxy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 views)",
    prevPrice: "$2000",
    newPrice: "1000",
    company: "Samsung",
    color: "white",
    category: "mobile",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.hPl5aHncakF3psTT5TLODAHaIw&pid=Api&P=0&h=180",
    title: "Smart Watche",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$5000",
    newPrice: "1000",
    company: "Apple",
    color: "white",
    category: "watches",
  },

  {
    img: "https://tse1.mm.bing.net/th?id=OIP.QbFCDy0mCC1nRPj58w5guAHaJ4&pid=Api&P=0&h=180",
    title: "Samsung Galaxy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$4000",
    newPrice: "1000",
    company: "Samsung",
    color: "blue",
    category: "mobile",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.-rerpszWseRRwSNM1tk1bAHaHa&pid=Api&P=0&h=180",
    title: "Sony Smart watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(144 reviews)",
    prevPrice: "$5000",
    newPrice: "1000",
    company: "Sony",
    color: "green",
    category: "watches",
  },

  {
    img: "https://tse1.mm.bing.net/th?id=OIP.cx0No6CRrEvqXR2ArEM8UAHaHa&pid=Api&P=0&h=180",
    title: "Sony digital camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$1000",
    newPrice: "150",
    company: "Sony",
    color: "green",
    category: "camera",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.mzm8248ZNJMc0Ird2WA3ywHaJL&pid=Api&P=0&h=180",
    title: "Samsung Galaxy",
    star: <AiFillStar className="rating-star" />,
    reviews: "(300 reviews)",
    prevPrice: "$5000",
    newPrice: "1000",
    company: "Samsung",
    color: "red",
    category:"mobile",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.Jr8rsfL_MjgMGzUG-LrJ0wHaHa&pid=Api&P=0&h=180",
    title: "Dell Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1200 reviews)",
    prevPrice: "$1000",
    newPrice: "100",
    company: "Dell",
    color: "black",
    category: "watches",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.lxCCTMAgf8x_mu7Lb5kJTgHaGL&pid=Api&P=0&h=180",
    title: "samsung 15.6 laptop ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$100000",
    newPrice: "10000",
    company: "Samsung",
    color: "white",
    category: "laptop",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.gWuRDb5xu2Srdb0mvl_m6wHaHa&pid=Api&P=0&h=180",
    title: "Sony Xperia 1 V",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1000 reviews)",
    prevPrice: "$1000",
    newPrice: "100",
    company: "Sony",
    color: "blue",
    category: "mobile",
  },

  {
    img: "https://tse3.mm.bing.net/th?id=OIP.45f3iLLTv6F7qaZ55d0QpwHaHa&pid=Api&P=0&h=180",
    title: "Apple smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$1000",
    newPrice: "150",
    company: "Apple",
    color: "black",
    category: "watches",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.5-0E5uePBT0joLIW_52qKgHaHa&pid=Api&P=0&h=180",
    title: "Apple Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(400 reviews)",
    prevPrice: "$400000",
    newPrice: "10000",
    company: "Apple",
    color: "red",
    category: "laptop",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.uYZSxViWEZbJXMMBQkCwkwHaHa&pid=Api&P=0&h=180",
    title: "Apple Watch Series1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3300 reviews)",
    prevPrice: "$100",
    newPrice: "150",
    company: "Apple",
    color: "pink",
    category: "watches",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.NPmHj2MJT2udkTdUZhAcPwHaFj&pid=Api&P=0&h=180",
    title: "Laptop Sony Vaio",
    star: <AiFillStar className="rating-star" />,
    reviews: "(5000 reviews)",
    prevPrice: "$40000",
    newPrice: "10000",
    company: "Sony",
    color: "blue",
    category: "laptop",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.JYriuVLeEpcTNpGjWFTFBwHaHa&pid=Api&P=0&h=180",
    title: "Apple Phone",
    star: <AiFillStar className="rating-star" />,
    reviews: "(8000 reviews)",
    prevPrice: "$30000",
    newPrice: "10000",
    company: "Apple",
    color: "black",
    category: "mobile",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.aXZGGSOaf7il3LXSHkTwagHaHn&pid=Api&P=0&h=180",
    title: "Apple Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(300 reviews)",
    prevPrice: "$140",
    newPrice: "100",
    company: "Apple",
    color: "black",
    category: "camera",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.c0jvDkaCGkDo80CrK9sV0AHaHa&pid=Api&P=0&h=180",
    title: "Dell Mobile Phone",
    star: <AiFillStar className="rating-star" />,
    reviews: "(400 reviews)",
    prevPrice: "$1500",
    newPrice: "100",
    company: "Dell",
    color: "black",
    category: "mobile",
  },
  {
    img: "https://i.pinimg.com/originals/26/e0/9e/26e09e79e434231b2a6959d91fd8a50b.jpg",
    title: "Sony New laptops",
    star: <AiFillStar className="rating-star" />,
    reviews: "(500 reviews)",
    prevPrice: "$200000",
    newPrice: "100000",
    company: "Sony",
    color: "red",
    category: "laptop",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.4MHf_bqcAW499pcB6Fr-JAHaHa&pid=Api&P=0&h=180",
    title: "Samsung Smartwatch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(500 reviews)",
    prevPrice: "$500",
    newPrice: "150",
    company: "Samsung",
    color: "blue",
    category: "watches",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.we1jHN0nbKhtiUSDy35hbwHaHa&pid=Api&P=0&h=180",
    title: "Apple MacBook ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(2000 reviews)",
    prevPrice: "$2000",
    newPrice: "150,",
    company: "Apple",
    color: "white",
    category: "laptop",
  },
  {
    img: "https://snpi.dell.com/snp/images/products/large/en-us~AA312310/AA312310.jpg",
    title: "Smart Watchs",
    star: <AiFillStar className="rating-star" />,
    reviews: "(300 reviews)",
    prevPrice: "$300",
    newPrice: "150",
    company: "Dell",
    color: "black",
    category: "watches",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.j3EaxNGEAfNB4SXivOAHqQHaHa&pid=Api&P=0&h=180",
    title: "Wi-Fi Digital Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3000 reviews)",
    prevPrice: "$1000",
    newPrice: "150",
    company: "Samsung",
    color: "pink",
    category: "camera",
  },
  {
    img: "https://i5.walmartimages.com/asr/32b3ca47-75ff-4612-a5f2-fb045571f181_1.97bf0c4d6918debf7fc9c576883ee72a.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
    title: "Used Dell 14Laptop ",
    about:"Used Dell 14"/" E6430 Laptop PC with Intel Core i5-3220M Processor, 8GB Memory, 256GB Solid State Drive and Windows 10 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(500 reviews)",
    prevPrice: "$30000",
    newPrice: "1000",
    company: "Dell",
    color: "black",
    category: "laptop",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.XqQi2pkN3SrEPVuVlPNP0wHaJz&pid=Api&P=0&h=180",
    title: "Apple iPhone 14",
    about:"Apple iPhone 14 (256GB) price in India starts from ₹60,900. It is available at lowest price on Amazon in India as on Mar 20, 2025. Take a look at Apple iPhone 14 (256GB) detailed specifications and features.",
    star: <AiFillStar className="rating-star" />,
    reviews: "(2000 reviews)",
    prevPrice: "$20000",
    newPrice: "10000",
    company: "Apple",
    color: "red",
    category: "mobile",
  },
];

export default data;